---
title: "Challenge Power with Data Science"
---

The chapter begins by introducing the redlining maps that have been widely created and used. They help secure the power and property values of white people only. Thus, it’s important to challenge such power to use data science to counter against the unequal power structures and work for more equity. Nevertheless, although people think data science technologies like machine learning predicts the future, it actually uses the past data to reflect on not only the past but also current social inequities. An instance would be the Equivant risk assessment algorithms because the questions it asks indirectly link to racism and inequities existed. In fact, it is those dominant groups of people with privileges that should be shown the harm of differentials of power. With this, it helps to prompt more people to take action. For instance, an algorithmic accountability bill was prompted by the New York City Council to tackle algorithmic discrimination. Yet, such evidence may be questioned by the institutions for not telling the truth because the statistics are not enough or not clean, or not comprehensive as expected. It may also yield deficit narratives that fail to describe the advantages of the group. Thus, it’s difficult to properly use data to take action. 

Again, one problem with data science is that people have cultural assumptions and personal preconceptions about its objectivity. Although the development of data ethics has been stressed, it’s hard to avoid biases. Ethics, biases, fairness, accountability, transparency, and understanding algorithms are important for data science and may solve problems, but they maintain the current structure of power. Therefore, a broader focus on data justice, oppression, equity, co-liberation, reflexivity, and understanding history, culture, and context have been stressed. It seems that data people should shoulder more responsibilities and possess more knowledge and understanding of their surroundings, the social contexts, the values, and so on. Data science students should not mainly focus on technical stuff like learning databases or algorithms, because the effect of a complete data science project can be long-lasting and serious that requires more accuracy and caution. Therefore, education about data ethics is crucial. In necessary cases, though idealistically speaking, I think they should also consult with sociologists or experts in other areas to assure the questions are well designed and the products target the right audience. Another point I appreciate is that the creators of the Local Lotto project constantly interrogate themselves and their process. It’s indeed data people’s responsibility to realize the many hidden pitfalls in working with data science and that the algorithms should be audited after their creation. 

