---
title: "Data, A Double Edged Sword"
---

The introduction focuses largely on the story of Christine Darden who was discriminated against in NASA because of her sex and her race. With the help of Gloria Champine who collected data about gender and rank, the fact that Darden and the other women were largely overlooked at work was presented straightforwardly to her boss, so that she finally got a promotion, something she deserved long ago. This story reminds me that I once attended an open lecture at Smith College where the speaker, also a Black female, shared her story where she used data to make reports to emphasize the fact that discriminations happen in her communities. It is surprising for many people that by presenting a statistical report, data solve problems in a seemingly easy way. This power of data creates empathy by letting others acknowledge some facts which people with other identities are experiencing at the moment. With intersectionality, what I think about is that people are divided into tiny circles where they are alike. It’s difficult to understand others with different social backgrounds and hobbies. Therefore, with someone placing a report made of collective data, we can admit things we were not aware of.

Nevertheless, how the data can be properly treated is crucial. As the article mentions, there are many people, including those who offer their information, those who collect the data, those who study and analyze the data, and those who visualize the data. Using data to make impacts is actually never simple, because every step matters and needs expertise to carry out. For instance, throughout history, there is much biased data that has been collected and misused. What’s more, people who offer their information may not tell the truth. Speaking of data collection, I’m also worried that people would find ways to fake information and data when their senses of insecurity grow out of the overcollection of personal information from government and corporations. For instance, people may make up personal stories by having multiple accounts, faking their life habits and so on. Even though data can do so much good to people, it’s still hard to use it well enough to satisfy the public.
