---
title: "Debatable Questions concerning Emotions and Counting"
---

The third chapter poses a question concerning whether emotions should be evoked by data visualizations. To some people like authors Nicole Amare and Alan Manning, the answer is no and they think that colors and icons also stir up emotions and prevent the audience from their rational thinking. Such people seek for neutrality, objectivity, clarity and truth when they uses data to produce outputs. Yet, “any communicating object that reflects choices about the selection and representation of reality is a rhetorical object”. An example from The New York Times is helpful in explaining the relationship between neutrality and truth. It created two graphics from the report where one comes from the perspective of Democrats and the other comes from that of Republicans. Both of them presented factual graphics, but since they had different focuses to interpret the job market, neither graphic is neutral. From this instance, we know that depending on the designers’ interests, graphics are interpreted differently and the audience has different take-aways. Therefore, Helen Kennedy and coauthors pointed out four conventions of data visualization to reinforce the factual side of graphics: “two-dimensional viewpoints, clean layouts, geometric shapes and lines, and the inclusion of data sources at the bottom.” Some people also raise theories for inviting people to the knowledge making processes and gather multiple standpoints to preserve the objectivity. It is important to embrace more and more positionalities to frame the whole work. As a result, it seems that by merely avoiding emotions, neutrality or objectivity cannot be preserved well. 

In fact, the designers can both leverage the emotions, but also preserve visual minimalism at the same time. Skilled data scientists are even pushing the boundaries to data visceralization that is also accessible to visual disabilities. For instance, a performance A Sort of Joy uses its live movements and sounds to make people feel and sense the gender differentials, rather than merely making them see the line trends. Projects like this aim to speak to certain parts of the human brains via multiple sensory perceptions. One difficulty with reading data visualization is that audiences are terrible at recognizing uncertainties and have misinterpretations when their brains make shortcuts to the conclusions. One solution for this is to show but not to tell the uncertainties. I do agree that for the audiences unfamiliar with statistics and computer science, it is so normal that they are misguided, especially when they trust the graphics so much.

In general, the debate is whether emotions make the visualizations less neutral and present with less objectivity. I believe psychological researches could help with investigating this question in terms of how different visuals affect people’s judgements. Till now, I don’t think there’s an single answer for this because there are indeed pros and cons coexisted for incorporating emotions into data visualizations. What I believe is graphics should create the best outcomes no matter it stirs emotions up or not.

The fourth chapter also talks about an ongoing debate. The beginning of the chapter talks back to the omission of data that is not collected. The problem stems partly from the classification systems for the fact that it is embedded with differential treatments for all kinds of people. Since data is filled with categories, it is impossible to get rid of classification systems. In fact, flawed classification systems mean inequality that upholds the hierarchies. Thus, when it comes to gender classifications, data scientists find it wiser to disaggregate gender data, to not make it binary, and to capture its fluidity. One important lesson I’ve learned from the two chapters is that making people visible isn’t necessarily good for it poses the minoritized groups at risk because even though their data can be recorded into the systems, their identities are not embraced by certain agencies or society. Here lie the ethical decisions for how data scientists should count their data. The authors point out “awarenesses of context and an analysis of power” which I think would be really helpful. How data should be treated should depends on the real situation and should be flexibly changed.

As some realize the harms of exposure in personal safety, people try to hide by faking their online identities and try to be as invisible as possible. Yet, it is still important to recognize the advantages of counting and making the minorities visible especially in the historical context. This goes back to my initiative of learning data science which is that aggregated data results can push and activate actions. By considering the diversity of different groups and taking these diversities into accounts, we can produce such data results. To protect the participants, we may also keep them private. The collecting issue is really a double sword.

In general, it’s crucial to think about whose benefits are preserved or enhanced before starting a project with data. I believe the idea for this book is about inclusion and prioritizing the minoritized groups and always consider their needs and suffers that are often ignored throughout history. By having such discussions, it’s not necessary to reach a definite conclusion such that counting some information or excluding emotions is wrong. I think rather than sticking to a debatable question, what we need to keep in mind is always whether we could reach an embracive and considerable outcome using data.

