---
title: "Chapter 1"
---

The first chapter talks about how power and privilege take roles in data science. In fact, minoritized groups not only suffer from oppression from a more powerful group in areas of politics, economics, gender, race and etc, but this oppression is baked into data science, including datasets, databases, and algorithms which we might not be aware of. Even the data scientists themselves might not know, because a privilege hazard, known as unintentional ignorance of the most privileged people, is well-spread. What’s more, this most privileged group of people, usually referred to as elite white males, happens to be the increasingly dominant group of data scientists in the field of computer science. Therefore, since the scientists are not fully aware of how their perspectives might be biased based on their class, race, and gender, the datasets they collect are often problematic. I like the saying that “data are never neutral” since the so-called intelligent technology is developed by people with biases and indifferences. The data developed by the elite white men might be used to work towards their advantages. Another problem is with missing data. Without enough care for the minoritized groups, governments or agencies are lack policies to implement data collections for them. The reason they don’t care always comes from power and privilege and it does little good to them. In fact, another driving force is profit. This also happens a lot with corporations gaining too much control over customers’ personal information in order to develop strategies to sell products. 

The whole chapter recognizes the problem of power that is embedded in data science. Yet, other than merely understanding the harmful mechanisms, it’s more crucial to change the situations. I’m especially touched by the data that there’s a steady decline in the number of women computer science students in the US. Though the data only ranges to 2010, it is true that some women graduates who are less qualified and less confident in their work values think that positions like “data analysts” are better choices than “data scientists” or “data engineers” for them. On the other hand, in Smith, the numbers of graduating students from SDS and CS departments have been increasing actually. This Smith bubble indeed helps in eliminating the effect of prejudices and biases of what women are adept at from the outside world. Since women are used to being devalued, I think it’s important to cheer for my own that I’m always able to gain more and more knowledge and work for highly valued jobs if I persist in this career.

The chapter points out one solution for reducing the effect of power is by educating people with privilege hazard and having more agencies willing to do comprehensive data collections. It’s disappointing that if the situation needs to be improved, the help of government or corporations would have a much greater impact than merely random people without orgazations. Thus, how we can make them weigh more on the importance of data feminism than their priviledge and profit is a question. 
